stages:
  - test

variables:
  PLAYWRIGHT_BROWSERS_PATH: "/usr/local/share/.cache/ms-playwright"

cache:
  paths:
    - /usr/local/share/.cache/ms-playwright

test_prod:
  stage: test
  image: mcr.microsoft.com/playwright:focal
  variables:
    ENVIRONMENT: "prod"
  before_script:
    - export $(cat .env.prod | xargs)
  script:
    - npm ci
    - npx playwright install
    - ENVIRONMENT=prod npx playwright test --config=playwright.config.ts
  only:
    - master # or the branch/tag that represents production

test_stage:
  stage: test
  image: mcr.microsoft.com/playwright:focal
  variables:
    ENVIRONMENT: ""
  before_script:
    - export $(cat .env | xargs)
  script:
    - npm ci
    - npx playwright install
    - npx playwright test --config=playwright.config.ts
  only:
    - develop # or the branch/tag that represents staging
